<?php
use Phinx\Seed\AbstractSeed;

/**
 * ArosAco seed.
 */
class ArosAcoSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'aro_id' => '1',
                'aco_id' => '1',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '3',
                'aro_id' => '4',
                'aco_id' => '263',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '4',
                'aro_id' => '4',
                'aco_id' => '264',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '5',
                'aro_id' => '3',
                'aco_id' => '144',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '6',
                'aro_id' => '3',
                'aco_id' => '145',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '7',
                'aro_id' => '3',
                'aco_id' => '3',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '8',
                'aro_id' => '3',
                'aco_id' => '146',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '9',
                'aro_id' => '5',
                'aco_id' => '1',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '10',
                'aro_id' => '5',
                'aco_id' => '473',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '11',
                'aro_id' => '5',
                'aco_id' => '469',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '12',
                'aro_id' => '5',
                'aco_id' => '470',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '13',
                'aro_id' => '5',
                'aco_id' => '466',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '14',
                'aro_id' => '5',
                'aco_id' => '464',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '15',
                'aro_id' => '5',
                'aco_id' => '463',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '16',
                'aro_id' => '5',
                'aco_id' => '872',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '17',
                'aro_id' => '5',
                'aco_id' => '465',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '18',
                'aro_id' => '5',
                'aco_id' => '468',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '19',
                'aro_id' => '5',
                'aco_id' => '471',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '20',
                'aro_id' => '5',
                'aco_id' => '472',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '21',
                'aro_id' => '5',
                'aco_id' => '467',
                '_create' => '-1',
                '_read' => '-1',
                '_update' => '-1',
                '_delete' => '-1',
            ],
            [
                'id' => '22',
                'aro_id' => '3',
                'aco_id' => '122',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '23',
                'aro_id' => '3',
                'aco_id' => '123',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '24',
                'aro_id' => '3',
                'aco_id' => '125',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '25',
                'aro_id' => '3',
                'aco_id' => '36',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '26',
                'aro_id' => '3',
                'aco_id' => '37',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '27',
                'aro_id' => '3',
                'aco_id' => '38',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '29',
                'aro_id' => '4',
                'aco_id' => '696',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '30',
                'aro_id' => '3',
                'aco_id' => '696',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '31',
                'aro_id' => '4',
                'aco_id' => '514',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '32',
                'aro_id' => '3',
                'aco_id' => '514',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '33',
                'aro_id' => '3',
                'aco_id' => '512',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '34',
                'aro_id' => '4',
                'aco_id' => '512',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '35',
                'aro_id' => '4',
                'aco_id' => '513',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '36',
                'aro_id' => '3',
                'aco_id' => '513',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '37',
                'aro_id' => '4',
                'aco_id' => '515',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '38',
                'aro_id' => '3',
                'aco_id' => '515',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '39',
                'aro_id' => '3',
                'aco_id' => '4',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
            [
                'id' => '40',
                'aro_id' => '3',
                'aco_id' => '152',
                '_create' => '1',
                '_read' => '1',
                '_update' => '1',
                '_delete' => '1',
            ],
        ];

        $table = $this->table('aros_acos');
        $table->insert($data)->save();
    }
}
