<?php
use Phinx\Seed\AbstractSeed;

/**
 * CompliancePackage seed.
 */
class CompliancePackageSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'package_id' => '1',
                'name' => 'Information Security Management Program',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '2',
                'package_id' => '2',
                'name' => 'Access Control Policy',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '3',
                'package_id' => '3',
                'name' => 'User Registration',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '4',
                'package_id' => '4',
                'name' => 'User Password Management',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '5',
                'package_id' => '5',
                'name' => 'Password Use',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '6',
                'package_id' => '6',
                'name' => 'Clear Desk and Clear Screen Policy',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '7',
                'package_id' => '7',
                'name' => 'Policy on Use of Network Services',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '8',
                'package_id' => '8',
                'name' => 'User Authentication for External Connections',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '9',
                'package_id' => '9',
                'name' => 'Segregation in Networks',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '10',
                'package_id' => '10',
                'name' => 'Network Connection Control',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '11',
                'package_id' => '11',
                'name' => 'Network Routing Control',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '12',
                'package_id' => '12',
                'name' => 'User Identification and Authentication',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '13',
                'package_id' => '13',
                'name' => 'Password Management System',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '14',
                'package_id' => '14',
                'name' => 'Information Access Restriction',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '15',
                'package_id' => '15',
                'name' => 'Sensitive System Isolation',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '16',
                'package_id' => '16',
                'name' => 'Mobile Computing and Communications',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '17',
                'package_id' => '17',
                'name' => 'Teleworking',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '18',
                'package_id' => '18',
                'name' => 'Roles and Responsibilities',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '19',
                'package_id' => '19',
                'name' => 'Management Responsibilities',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '20',
                'package_id' => '20',
                'name' => 'Information Security Awareness, Education,
and Training',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '21',
                'package_id' => '21',
                'name' => 'Disciplinary Process',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '22',
                'package_id' => '22',
                'name' => 'Removal of Access Rights',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '23',
                'package_id' => '23',
                'name' => 'Risk Management Program Development',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '24',
                'package_id' => '24',
                'name' => 'Performing Risk Assessment',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '25',
                'package_id' => '25',
                'name' => 'Risk Mitigation',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '26',
                'package_id' => '26',
                'name' => 'Information Security Policy Document',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '27',
                'package_id' => '27',
                'name' => 'Review of the Information Security Policy',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '28',
                'package_id' => '28',
                'name' => 'Management Commitment to Information Security',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '29',
                'package_id' => '29',
                'name' => 'Information Security Coordination',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '30',
                'package_id' => '30',
                'name' => 'Identification of Risks Related to External Parties',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '31',
                'package_id' => '31',
                'name' => 'Addressing Security in Third Party Agreements',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '32',
                'package_id' => '32',
                'name' => 'Data Protection and Privacy of Covered Information',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '33',
                'package_id' => '33',
                'name' => 'Prevention of Misuse of Information Assets',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '34',
                'package_id' => '34',
                'name' => 'Compliance with Security Policies and Standards',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '35',
                'package_id' => '35',
                'name' => 'Inventory of Assets',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '36',
                'package_id' => '36',
                'name' => 'Acceptable Use of Assets',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:40',
                'modified' => '2017-04-10 13:55:40',
            ],
            [
                'id' => '37',
                'package_id' => '37',
                'name' => 'Physical Entry of Controls',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '38',
                'package_id' => '38',
                'name' => 'Protecting Against External and Environmental Threats',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '39',
                'package_id' => '39',
                'name' => 'Equipment Maintenance',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '40',
                'package_id' => '40',
                'name' => 'Secure Disposal or Re-Use of Equipment',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '41',
                'package_id' => '41',
                'name' => 'Audit Logging',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '42',
                'package_id' => '42',
                'name' => 'Monitoring System Use',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '43',
                'package_id' => '43',
                'name' => 'Protection of Log Information',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '44',
                'package_id' => '44',
                'name' => 'Clock Synchronization',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '45',
                'package_id' => '45',
                'name' => 'Segregation of Duties',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '46',
                'package_id' => '46',
                'name' => 'Service Delivery',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '47',
                'package_id' => '47',
                'name' => 'Monitoring and Review of Third Party Services',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '48',
                'package_id' => '48',
                'name' => 'Managing Changes to Third Party Services',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '49',
                'package_id' => '49',
                'name' => 'Controls Against Malicious Code',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '50',
                'package_id' => '50',
                'name' => 'Network Controls',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '51',
                'package_id' => '51',
                'name' => 'Security of Network Services',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '52',
                'package_id' => '52',
                'name' => 'Management of Removable Media',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '53',
                'package_id' => '53',
                'name' => 'Disposal of Media',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '54',
                'package_id' => '54',
                'name' => 'Information Handling Procedures',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '55',
                'package_id' => '55',
                'name' => 'Information Exchange Policies and Procedures',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '56',
                'package_id' => '56',
                'name' => 'Input Data Validation',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '57',
                'package_id' => '57',
                'name' => 'Policy on the Use of Cryptographic Controls',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '58',
                'package_id' => '58',
                'name' => 'Key Management',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '59',
                'package_id' => '59',
                'name' => 'Control of Operational Software',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '60',
                'package_id' => '60',
                'name' => 'Outsourced Software Development',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '61',
                'package_id' => '61',
                'name' => 'Control of Technical Vulnerabilities',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '62',
                'package_id' => '62',
                'name' => 'Reporting Information Security Events',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '63',
                'package_id' => '63',
                'name' => 'Responsibilities and Procedures',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '64',
                'package_id' => '64',
                'name' => 'Developing and Implementing Continuity Plans Including Information Security',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '3',
                'created' => '2017-04-10 13:55:41',
                'modified' => '2017-04-10 13:55:41',
            ],
            [
                'id' => '65',
                'package_id' => '1',
                'name' => 'Requirement 1: Install and maintain a firewall configuration to protect cardholder data',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:03',
                'modified' => '2017-04-10 13:56:03',
            ],
            [
                'id' => '66',
                'package_id' => '2',
                'name' => 'Requirement 2: Do not use vendor-supplied defaults for system passwords and other security parameter',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:03',
                'modified' => '2017-04-10 13:56:03',
            ],
            [
                'id' => '67',
                'package_id' => '3',
                'name' => 'Requirement 3: Protect stored cardholder data',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:03',
                'modified' => '2017-04-10 13:56:03',
            ],
            [
                'id' => '68',
                'package_id' => '4',
                'name' => 'Requirement 4: Encrypt transmission of cardholder data across open; public networks',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:03',
                'modified' => '2017-04-10 13:56:03',
            ],
            [
                'id' => '69',
                'package_id' => '5',
                'name' => 'Requirement 5: Use and regularly update anti-virus software or programs',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:03',
                'modified' => '2017-04-10 13:56:03',
            ],
            [
                'id' => '70',
                'package_id' => '6',
                'name' => 'Requirement 6: Develop and maintain secure systems and applications',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:03',
                'modified' => '2017-04-10 13:56:03',
            ],
            [
                'id' => '71',
                'package_id' => '7',
                'name' => 'Requirement 7: Restrict access to cardholder data by business need to know',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:03',
                'modified' => '2017-04-10 13:56:03',
            ],
            [
                'id' => '72',
                'package_id' => '8',
                'name' => 'Requirement 8: Assign a unique ID to each person with computer access',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:03',
                'modified' => '2017-04-10 13:56:03',
            ],
            [
                'id' => '73',
                'package_id' => '9',
                'name' => 'Requirement 9: Restrict physical access to cardholder data',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:03',
                'modified' => '2017-04-10 13:56:03',
            ],
            [
                'id' => '74',
                'package_id' => '10',
                'name' => 'Requirement 10: Track and monitor all access to network resources and cardholder data',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:03',
                'modified' => '2017-04-10 13:56:03',
            ],
            [
                'id' => '75',
                'package_id' => '11',
                'name' => 'Requirement 11: Regularly test security systems and processes',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:04',
                'modified' => '2017-04-10 13:56:04',
            ],
            [
                'id' => '76',
                'package_id' => '12',
                'name' => 'Requirement 12: Maintain a policy that addresses information security for all personnel',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:04',
                'modified' => '2017-04-10 13:56:04',
            ],
            [
                'id' => '77',
                'package_id' => 'A1',
                'name' => 'Appendix A1: Additional PCI DSS Requirements for Shared Hosting Providers',
                'description' => 'NA',
                'third_party_id' => '4',
                'created' => '2017-04-10 13:56:04',
                'modified' => '2017-04-10 13:56:04',
            ],
            [
                'id' => '78',
                'package_id' => '5.1',
                'name' => 'Information Security Policy',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '79',
                'package_id' => '6.1',
                'name' => 'Internal Organization',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '80',
                'package_id' => '6.2',
                'name' => 'Mobile devices and teleworking',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '81',
                'package_id' => '7.1',
                'name' => 'Prior to Employment',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '82',
                'package_id' => '7.2',
                'name' => 'During Employment',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '83',
                'package_id' => '7.3',
                'name' => 'Termination or change of employment',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '84',
                'package_id' => '8.1',
                'name' => 'Prior to Employment',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '85',
                'package_id' => '8.2',
                'name' => 'Information Classification',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '86',
                'package_id' => '8.3',
                'name' => 'Media Handling',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '87',
                'package_id' => '9.1',
                'name' => 'Business Requirement for Access Control',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '88',
                'package_id' => '9.2',
                'name' => 'User access Management',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '89',
                'package_id' => '9.3',
                'name' => 'User Responsabilties',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '90',
                'package_id' => '9.4',
                'name' => 'System and application access control',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '91',
                'package_id' => '10.1',
                'name' => 'Cryptographic controls',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '92',
                'package_id' => '11.1',
                'name' => 'Physical and enviromental security',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '93',
                'package_id' => '11.2',
                'name' => 'Equipment',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '94',
                'package_id' => '12.1',
                'name' => 'Operational procedures and responsabilities',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '95',
                'package_id' => '12.2',
                'name' => 'Protection from Malware',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '96',
                'package_id' => '12.3',
                'name' => 'Backup',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '97',
                'package_id' => '12.4',
                'name' => 'Logging and Monitoring',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '98',
                'package_id' => '12.5',
                'name' => 'Control of operational software',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '99',
                'package_id' => '12.6',
                'name' => 'Technical vulnerability management',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '100',
                'package_id' => '12.7',
                'name' => 'Information System audit considerations',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '101',
                'package_id' => '13.1',
                'name' => 'Network Security Management',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '102',
                'package_id' => '13.2',
                'name' => 'Information Transfer',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '103',
                'package_id' => '14.1',
                'name' => 'Security Requirements of information systems',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '104',
                'package_id' => '14.2',
                'name' => 'Security in Development &amp; Support Processes',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '105',
                'package_id' => '14.3',
                'name' => 'Test Data',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '106',
                'package_id' => '15.1',
                'name' => 'Information security in supplier relationships',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '107',
                'package_id' => '15.2',
                'name' => 'Supplier service delivery management',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '108',
                'package_id' => '16.1',
                'name' => 'Management of Information Security Incidents and Improvements',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '109',
                'package_id' => '17.1',
                'name' => 'Information Security Continuity',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '110',
                'package_id' => '17.2',
                'name' => 'Reundancies',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '111',
                'package_id' => '18.1',
                'name' => 'Compliance with Legal and Contractual Requirements',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '112',
                'package_id' => '18.2',
                'name' => 'Information Security Reviews',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:35',
                'modified' => '2017-04-10 13:58:35',
            ],
            [
                'id' => '113',
                'package_id' => '5.1',
                'name' => 'Information Security Policy',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '114',
                'package_id' => '6.1',
                'name' => 'Internal Organization',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '115',
                'package_id' => '6.2',
                'name' => 'Mobile devices and teleworking',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '116',
                'package_id' => '7.1',
                'name' => 'Prior to Employment',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '117',
                'package_id' => '7.2',
                'name' => 'During Employment',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '118',
                'package_id' => '7.3',
                'name' => 'Termination or change of employment',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '119',
                'package_id' => '8.1',
                'name' => 'Prior to Employment',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '120',
                'package_id' => '8.2',
                'name' => 'Information Classification',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '121',
                'package_id' => '8.3',
                'name' => 'Media Handling',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '122',
                'package_id' => '9.1',
                'name' => 'Business Requirement for Access Control',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '123',
                'package_id' => '9.2',
                'name' => 'User access Management',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '124',
                'package_id' => '9.3',
                'name' => 'User Responsabilties',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '125',
                'package_id' => '9.4',
                'name' => 'System and application access control',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '126',
                'package_id' => '10.1',
                'name' => 'Cryptographic controls',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '127',
                'package_id' => '11.1',
                'name' => 'Physical and enviromental security',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '128',
                'package_id' => '11.2',
                'name' => 'Equipment',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '129',
                'package_id' => '12.1',
                'name' => 'Operational procedures and responsabilities',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '130',
                'package_id' => '12.2',
                'name' => 'Protection from Malware',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '131',
                'package_id' => '12.3',
                'name' => 'Backup',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '132',
                'package_id' => '12.4',
                'name' => 'Logging and Monitoring',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '133',
                'package_id' => '12.5',
                'name' => 'Control of operational software',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '134',
                'package_id' => '12.6',
                'name' => 'Technical vulnerability management',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '135',
                'package_id' => '12.7',
                'name' => 'Information System audit considerations',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '136',
                'package_id' => '13.1',
                'name' => 'Network Security Management',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '137',
                'package_id' => '13.2',
                'name' => 'Information Transfer',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '138',
                'package_id' => '14.1',
                'name' => 'Security Requirements of information systems',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '139',
                'package_id' => '14.2',
                'name' => 'Security in Development &amp; Support Processes',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '140',
                'package_id' => '14.3',
                'name' => 'Test Data',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '141',
                'package_id' => '15.1',
                'name' => 'Information security in supplier relationships',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '142',
                'package_id' => '15.2',
                'name' => 'Supplier service delivery management',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '143',
                'package_id' => '16.1',
                'name' => 'Management of Information Security Incidents and Improvements',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '144',
                'package_id' => '17.1',
                'name' => 'Information Security Continuity',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '145',
                'package_id' => '17.2',
                'name' => 'Reundancies',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '146',
                'package_id' => '18.1',
                'name' => 'Compliance with Legal and Contractual Requirements',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '147',
                'package_id' => '18.2',
                'name' => 'Information Security Reviews',
                'description' => 'Not Specified',
                'third_party_id' => '2',
                'created' => '2017-04-10 13:58:36',
                'modified' => '2017-04-10 13:58:36',
            ],
            [
                'id' => '170',
                'package_id' => '1',
                'name' => 'Information Security Management Program',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '5',
                'created' => '2017-04-10 15:59:44',
                'modified' => '2017-04-10 15:59:44',
            ],
            [
                'id' => '171',
                'package_id' => '2',
                'name' => 'Access Control Policy',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '5',
                'created' => '2017-04-10 15:59:44',
                'modified' => '2017-04-10 15:59:44',
            ],
            [
                'id' => '172',
                'package_id' => '3',
                'name' => 'User Registration',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '5',
                'created' => '2017-04-10 15:59:44',
                'modified' => '2017-04-10 15:59:44',
            ],
            [
                'id' => '173',
                'package_id' => '4',
                'name' => 'User Password Management',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '5',
                'created' => '2017-04-10 15:59:44',
                'modified' => '2017-04-10 15:59:44',
            ],
            [
                'id' => '174',
                'package_id' => '5',
                'name' => 'Password Use',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '5',
                'created' => '2017-04-10 15:59:44',
                'modified' => '2017-04-10 15:59:44',
            ],
            [
                'id' => '175',
                'package_id' => '6',
                'name' => 'Clear Desk and Clear Screen Policy',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '5',
                'created' => '2017-04-10 15:59:44',
                'modified' => '2017-04-10 15:59:44',
            ],
            [
                'id' => '176',
                'package_id' => '7',
                'name' => 'Policy on Use of Network Services',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '5',
                'created' => '2017-04-10 15:59:44',
                'modified' => '2017-04-10 15:59:44',
            ],
            [
                'id' => '177',
                'package_id' => '8',
                'name' => 'User Authentication for External Connections',
                'description' => 'HIPAA HITRUST',
                'third_party_id' => '5',
                'created' => '2017-04-10 15:59:44',
                'modified' => '2017-04-10 15:59:44',
            ],
            [
                'id' => '178',
                'package_id' => '1',
                'name' => 'Restrict Internet Access &amp; Protect Critical Systems from General IT Environment',
                'description' => 'not specified',
                'third_party_id' => '7',
                'created' => '2017-04-12 07:59:08',
                'modified' => '2017-04-12 07:59:08',
            ],
            [
                'id' => '179',
                'package_id' => '2',
                'name' => 'Reduce Attack Surface and Vulnerabilities',
                'description' => 'not specified',
                'third_party_id' => '7',
                'created' => '2017-04-12 07:59:08',
                'modified' => '2017-04-12 07:59:08',
            ],
            [
                'id' => '180',
                'package_id' => '3',
                'name' => 'Physically Secure the Environment',
                'description' => 'not specified',
                'third_party_id' => '7',
                'created' => '2017-04-12 07:59:08',
                'modified' => '2017-04-12 07:59:08',
            ],
            [
                'id' => '181',
                'package_id' => '4',
                'name' => 'Prevent Compromise of Credentials',
                'description' => 'not specified',
                'third_party_id' => '7',
                'created' => '2017-04-12 07:59:08',
                'modified' => '2017-04-12 07:59:08',
            ],
            [
                'id' => '182',
                'package_id' => '5',
                'name' => 'Manage Identities and Segregate Privileges',
                'description' => 'not specified',
                'third_party_id' => '7',
                'created' => '2017-04-12 07:59:08',
                'modified' => '2017-04-12 07:59:08',
            ],
            [
                'id' => '183',
                'package_id' => '6',
                'name' => 'Detect Anomalous Activity to Systems or Transaction Records',
                'description' => 'not specified',
                'third_party_id' => '7',
                'created' => '2017-04-12 07:59:08',
                'modified' => '2017-04-12 07:59:08',
            ],
            [
                'id' => '184',
                'package_id' => '7',
                'name' => 'Plan for Incident Response and Information Sharing',
                'description' => 'not specified',
                'third_party_id' => '7',
                'created' => '2017-04-12 07:59:08',
                'modified' => '2017-04-12 07:59:08',
            ],
        ];

        $table = $this->table('compliance_packages');
        $table->insert($data)->save();
    }
}
