<?php
use Phinx\Seed\AbstractSeed;

/**
 * ComplianceManagement seed.
 */
class ComplianceManagementSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'compliance_package_item_id' => '1',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => '2',
                'efficacy' => '90',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:19:19',
                'modified' => '2017-04-10 14:19:19',
            ],
            [
                'id' => '2',
                'compliance_package_item_id' => '2',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => '1',
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:20:01',
                'modified' => '2017-04-10 14:20:01',
            ],
            [
                'id' => '3',
                'compliance_package_item_id' => '3',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:20:42',
                'modified' => '2017-04-10 14:20:42',
            ],
            [
                'id' => '4',
                'compliance_package_item_id' => '4',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:20:59',
                'modified' => '2017-04-10 14:20:59',
            ],
            [
                'id' => '5',
                'compliance_package_item_id' => '5',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:21:28',
                'modified' => '2017-04-10 14:21:28',
            ],
            [
                'id' => '6',
                'compliance_package_item_id' => '6',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:21:38',
                'modified' => '2017-04-10 14:21:38',
            ],
            [
                'id' => '7',
                'compliance_package_item_id' => '7',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:21:55',
                'modified' => '2017-04-10 14:21:55',
            ],
            [
                'id' => '8',
                'compliance_package_item_id' => '8',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:22:32',
                'modified' => '2017-04-10 14:22:32',
            ],
            [
                'id' => '9',
                'compliance_package_item_id' => '10',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:22:53',
                'modified' => '2017-04-10 14:22:53',
            ],
            [
                'id' => '10',
                'compliance_package_item_id' => '9',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:24:17',
                'modified' => '2017-04-10 14:24:17',
            ],
            [
                'id' => '11',
                'compliance_package_item_id' => '11',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:25:09',
                'modified' => '2017-04-10 14:25:09',
            ],
            [
                'id' => '12',
                'compliance_package_item_id' => '13',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:25:40',
                'modified' => '2017-04-10 14:25:40',
            ],
            [
                'id' => '13',
                'compliance_package_item_id' => '37',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:26:18',
                'modified' => '2017-04-10 14:26:18',
            ],
            [
                'id' => '14',
                'compliance_package_item_id' => '65',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:27:24',
                'modified' => '2017-04-10 14:27:24',
            ],
            [
                'id' => '15',
                'compliance_package_item_id' => '66',
                'compliance_treatment_strategy_id' => '3',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '0',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:28:09',
                'modified' => '2017-04-10 14:28:38',
            ],
            [
                'id' => '16',
                'compliance_package_item_id' => '68',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:30:11',
                'modified' => '2017-04-10 14:30:11',
            ],
            [
                'id' => '17',
                'compliance_package_item_id' => '69',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '90',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:30:37',
                'modified' => '2017-04-10 14:30:37',
            ],
            [
                'id' => '18',
                'compliance_package_item_id' => '67',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:30:57',
                'modified' => '2017-04-10 14:30:57',
            ],
            [
                'id' => '19',
                'compliance_package_item_id' => '324',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:32:51',
                'modified' => '2017-04-10 14:32:51',
            ],
            [
                'id' => '20',
                'compliance_package_item_id' => '325',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:33:05',
                'modified' => '2017-04-10 14:33:05',
            ],
            [
                'id' => '21',
                'compliance_package_item_id' => '327',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:33:25',
                'modified' => '2017-04-10 14:33:25',
            ],
            [
                'id' => '22',
                'compliance_package_item_id' => '328',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:33:41',
                'modified' => '2017-04-10 14:33:41',
            ],
            [
                'id' => '23',
                'compliance_package_item_id' => '329',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:33:58',
                'modified' => '2017-04-10 14:33:58',
            ],
            [
                'id' => '24',
                'compliance_package_item_id' => '332',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:34:46',
                'modified' => '2017-04-10 14:34:46',
            ],
            [
                'id' => '25',
                'compliance_package_item_id' => '331',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:35:08',
                'modified' => '2017-04-10 14:35:08',
            ],
            [
                'id' => '26',
                'compliance_package_item_id' => '333',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:35:39',
                'modified' => '2017-04-10 14:35:39',
            ],
            [
                'id' => '27',
                'compliance_package_item_id' => '334',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:36:08',
                'modified' => '2017-04-10 14:36:08',
            ],
            [
                'id' => '28',
                'compliance_package_item_id' => '340',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:36:41',
                'modified' => '2017-04-10 14:36:41',
            ],
            [
                'id' => '29',
                'compliance_package_item_id' => '339',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:37:29',
                'modified' => '2017-04-10 14:37:29',
            ],
            [
                'id' => '30',
                'compliance_package_item_id' => '341',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => NULL,
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '100',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:37:51',
                'modified' => '2017-04-10 14:37:51',
            ],
            [
                'id' => '31',
                'compliance_package_item_id' => '337',
                'compliance_treatment_strategy_id' => '1',
                'compliance_exception_id' => '1',
                'legal_id' => NULL,
                'owner_id' => NULL,
                'efficacy' => '0',
                'description' => '',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:42:02',
                'modified' => '2017-04-10 14:42:02',
            ],
        ];

        $table = $this->table('compliance_managements');
        $table->insert($data)->save();
    }
}
