<?php
use Phinx\Seed\AbstractSeed;

/**
 * Review seed.
 */
class ReviewSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'model' => 'SecurityPolicy',
                'foreign_key' => '1',
                'planned_date' => '2017-12-31',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '2',
                'model' => 'SecurityPolicy',
                'foreign_key' => '2',
                'planned_date' => '2017-05-01',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '3',
                'model' => 'SecurityPolicy',
                'foreign_key' => '3',
                'planned_date' => '2017-04-11',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '4',
                'model' => 'SecurityPolicy',
                'foreign_key' => '4',
                'planned_date' => '2017-07-21',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '5',
                'model' => 'SecurityPolicy',
                'foreign_key' => '5',
                'planned_date' => '2017-05-24',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '6',
                'model' => 'SecurityPolicy',
                'foreign_key' => '6',
                'planned_date' => '2017-04-11',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '7',
                'model' => 'SecurityPolicy',
                'foreign_key' => '7',
                'planned_date' => '2017-12-06',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '8',
                'model' => 'SecurityPolicy',
                'foreign_key' => '8',
                'planned_date' => '2017-09-13',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '9',
                'model' => 'SecurityPolicy',
                'foreign_key' => '9',
                'planned_date' => '2017-09-27',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '10',
                'model' => 'SecurityPolicy',
                'foreign_key' => '10',
                'planned_date' => '2017-05-13',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '11',
                'model' => 'SecurityPolicy',
                'foreign_key' => '11',
                'planned_date' => '2017-07-05',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '12',
                'model' => 'SecurityPolicy',
                'foreign_key' => '12',
                'planned_date' => '2017-10-06',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '13',
                'model' => 'SecurityPolicy',
                'foreign_key' => '13',
                'planned_date' => '2017-11-27',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '14',
                'model' => 'SecurityPolicy',
                'foreign_key' => '14',
                'planned_date' => '2017-06-22',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '15',
                'model' => 'SecurityPolicy',
                'foreign_key' => '15',
                'planned_date' => '2018-01-14',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '16',
                'model' => 'SecurityPolicy',
                'foreign_key' => '16',
                'planned_date' => '2018-01-15',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '17',
                'model' => 'SecurityPolicy',
                'foreign_key' => '17',
                'planned_date' => '2018-01-16',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '18',
                'model' => 'SecurityPolicy',
                'foreign_key' => '18',
                'planned_date' => '2018-01-17',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '19',
                'model' => 'SecurityPolicy',
                'foreign_key' => '19',
                'planned_date' => '2018-01-18',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '20',
                'model' => 'SecurityPolicy',
                'foreign_key' => '20',
                'planned_date' => '2018-01-19',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '21',
                'model' => 'SecurityPolicy',
                'foreign_key' => '21',
                'planned_date' => '2018-01-20',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '22',
                'model' => 'SecurityPolicy',
                'foreign_key' => '22',
                'planned_date' => '2018-01-21',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '23',
                'model' => 'SecurityPolicy',
                'foreign_key' => '23',
                'planned_date' => '2018-01-22',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '24',
                'model' => 'SecurityPolicy',
                'foreign_key' => '24',
                'planned_date' => '2018-01-23',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '25',
                'model' => 'SecurityPolicy',
                'foreign_key' => '25',
                'planned_date' => '2018-01-24',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '26',
                'model' => 'SecurityPolicy',
                'foreign_key' => '26',
                'planned_date' => '2018-01-25',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '27',
                'model' => 'SecurityPolicy',
                'foreign_key' => '27',
                'planned_date' => '2018-01-26',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '28',
                'model' => 'SecurityPolicy',
                'foreign_key' => '28',
                'planned_date' => '2018-01-27',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '29',
                'model' => 'SecurityPolicy',
                'foreign_key' => '29',
                'planned_date' => '2017-06-22',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:15:38',
                'modified' => '2017-04-10 14:15:38',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '30',
                'model' => 'SecurityPolicy',
                'foreign_key' => '29',
                'planned_date' => '2017-04-10',
                'actual_date' => '2017-04-10',
                'user_id' => '1',
                'description' => 'Initial Upload',
                'completed' => '1',
                'version' => '4.5',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:16:27',
                'modified' => '2017-04-10 14:16:27',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '31',
                'model' => 'SecurityPolicy',
                'foreign_key' => '30',
                'planned_date' => '2017-09-29',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:23:54',
                'modified' => '2017-04-10 14:23:54',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '32',
                'model' => 'SecurityPolicy',
                'foreign_key' => '31',
                'planned_date' => '2017-04-30',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:29:23',
                'modified' => '2017-04-10 14:29:23',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '33',
                'model' => 'Asset',
                'foreign_key' => '13',
                'planned_date' => '2017-01-31',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 15:50:45',
                'modified' => '2017-04-10 15:50:46',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '34',
                'model' => 'SecurityPolicy',
                'foreign_key' => '1',
                'planned_date' => '2017-04-11',
                'actual_date' => '2017-04-11',
                'user_id' => '1',
                'description' => 'We updated some wording around change requests when handling private keys.',
                'completed' => '1',
                'version' => '2.1',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:42:17',
                'modified' => '2017-04-11 12:42:17',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '35',
                'model' => 'SecurityPolicy',
                'foreign_key' => '32',
                'planned_date' => '2017-08-31',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:55',
                'modified' => '2017-04-11 12:43:55',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '36',
                'model' => 'SecurityPolicy',
                'foreign_key' => '33',
                'planned_date' => '2017-08-22',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:55',
                'modified' => '2017-04-11 12:43:55',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '37',
                'model' => 'SecurityPolicy',
                'foreign_key' => '34',
                'planned_date' => '2017-08-30',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '38',
                'model' => 'SecurityPolicy',
                'foreign_key' => '35',
                'planned_date' => '2017-08-21',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '39',
                'model' => 'SecurityPolicy',
                'foreign_key' => '36',
                'planned_date' => '2017-08-30',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '40',
                'model' => 'SecurityPolicy',
                'foreign_key' => '37',
                'planned_date' => '2017-08-30',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '41',
                'model' => 'SecurityPolicy',
                'foreign_key' => '38',
                'planned_date' => '2017-11-07',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '42',
                'model' => 'SecurityPolicy',
                'foreign_key' => '39',
                'planned_date' => '2017-05-31',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '43',
                'model' => 'SecurityPolicy',
                'foreign_key' => '40',
                'planned_date' => '2017-10-24',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '44',
                'model' => 'SecurityPolicy',
                'foreign_key' => '41',
                'planned_date' => '2017-07-10',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '45',
                'model' => 'SecurityPolicy',
                'foreign_key' => '42',
                'planned_date' => '2017-11-13',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '46',
                'model' => 'Risk',
                'foreign_key' => '1',
                'planned_date' => '2017-05-31',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 13:05:33',
                'modified' => '2017-04-11 13:05:33',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '47',
                'model' => 'Risk',
                'foreign_key' => '2',
                'planned_date' => '2017-08-31',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 13:07:37',
                'modified' => '2017-04-11 13:07:37',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '48',
                'model' => 'ThirdPartyRisk',
                'foreign_key' => '1',
                'planned_date' => '2017-08-31',
                'actual_date' => NULL,
                'user_id' => '1',
                'description' => '',
                'completed' => '0',
                'version' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 13:25:23',
                'modified' => '2017-04-11 13:25:23',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '49',
                'model' => 'SecurityPolicy',
                'foreign_key' => '1',
                'planned_date' => '2017-04-11',
                'actual_date' => '2017-04-11',
                'user_id' => '1',
                'description' => 'Minor changes o the policy',
                'completed' => '1',
                'version' => '2.2',
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 13:47:25',
                'modified' => '2017-04-11 13:47:25',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
        ];

        $table = $this->table('reviews');
        $table->insert($data)->save();
    }
}
