<?php
use Phinx\Seed\AbstractSeed;

/**
 * SecurityPolicy seed.
 */
class SecurityPolicySeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'index' => 'Acceptable Encryption Policy',
                'short_description' => 'Outlines the requirement around which encryption algorithms (e.g. received substantial public review and have been proven to work effectively) are acceptable for use within the enterprise.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy/2.2',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '2.2',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-12-31',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '2',
                'index' => 'Acceptable Use Policy',
                'short_description' => 'Defines acceptable use of equipment and computing services, and the appropriate employee security measures to protect the organization\'s corporate resources and proprietary information.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-05-01',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '3',
                'index' => 'Clean Desk Policy',
                'short_description' => 'Defines the minimum requirements for maintaining a "clean desk" - where sensitive/critical information about our employees, our intellectual property, our customers and our vendors is secure in locked areas and out of sight.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-04-11',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '1',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-12 07:47:44',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '4',
                'index' => 'Data Breach Response Policy',
                'short_description' => 'Defines the goals and the vision for the breach response process. This policy defines to whom it applies and under what circumstances, and it will include the definition of a breach, staff roles and responsibilities, standards and metrics (e.g., to enable',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'procedure',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-07-21',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '5',
                'index' => 'Disaster Recovery Plan Policy',
                'short_description' => 'Defines the requirement for a baseline disaster recovery plan to be developed and implemented by the company, which describes the process to recover IT Systems, Applications and Data from any type of disaster that causes a major outage.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'procedure',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-05-24',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '6',
                'index' => 'Digital Signature Acceptance Policy',
                'short_description' => 'Defines the requirements for when a digital signature is considered an accepted means of validating the identity of a signer in electronic documents and correspondence, and thus a substitute for traditional "wet" signatures, within the organization.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-04-11',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '1',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-12 07:47:44',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '7',
                'index' => 'Email Policy',
                'short_description' => 'Defines the requirements for proper use of the company email system and make users aware of what is considered acceptable and unacceptable use of its email system.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-12-06',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '8',
                'index' => 'Ethics Policy',
                'short_description' => 'Defines the guidelines and expectations of individuals within the company to demonstrate fair business practices and encourage a culture of openness and trust.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-09-13',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '9',
                'index' => 'Pandemic Response Planning Policy',
                'short_description' => 'Defines the requirements for planning, preparation and performing exercises for pandemic disease outbreak over and above the normal business continuity and disaster recovery planning process.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-09-27',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '10',
                'index' => 'Password Construction Guidelines',
                'short_description' => 'Defines the guidelines and best practices for the creation of strong passwords.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-05-13',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '11',
                'index' => 'Password Protection Policy',
                'short_description' => 'Defines the standard for the creation of strong passwords, the protection of those passwords, and the frequency of change.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-07-05',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '12',
                'index' => 'Security Response Plan Policy',
                'short_description' => 'Defines the requirement for business units supported by the Infosec Team to develop and maintain a security response plan.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-10-06',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '13',
                'index' => 'End User Encryption Key Protection Policy',
                'short_description' => 'Defines the requirements for protecting encryption keys that are under the control of end users.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/general#acceptable-encryption-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-11-27',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '14',
                'index' => 'Acquisition Assessment Policy',
                'short_description' => 'Defines responsibilities regarding corporate acquisitions, and defines the minimum requirements of an acquisition assessment to be completed by the Infosec Team.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-06-22',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '15',
                'index' => 'Bluetooth Baseline Requirements Policy',
                'short_description' => 'Defines the minimum baseline standard for connecting Bluetooth enabled devices to the enterprise network or company owned devices. The intent of the minimum standard is to ensure sufficient protection Personally Identifiable Information (PII) and confiden',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-14',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '16',
                'index' => 'Remote Access Policy',
                'short_description' => 'Defines standards for connecting to the organization\'s network from any host or network external to the organization.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-15',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '17',
                'index' => 'Remote Access Tools Policy',
                'short_description' => 'Defines the requirements for what type of remote desktop software can be used and how it must be configured.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-16',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '18',
                'index' => 'Router and Switch Security Policy',
                'short_description' => 'Defines standards for minimal security configuration for routers and switches inside a production network, or used in a production capacity.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-17',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '19',
                'index' => 'Wireless Communication Policy',
                'short_description' => 'Defines the requirement for wireless infrastructure devices to adhere to wireless communication policy in order to connect to the company network.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-18',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '20',
                'index' => 'Wireless Communication Standard',
                'short_description' => 'Defines the technical requirements that wireless infrastructure devices must satisfy in order to connect to the company network.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-19',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '21',
                'index' => 'Database Credentials Policy',
                'short_description' => 'Defines the requirements for securely storing and retrieving database usernames and passwords (i.e., database credentials) for use by a program that will access a database running on one of companyâs networks.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-20',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '22',
                'index' => 'Technology Equipment Disposal Policy',
                'short_description' => 'Defines the requirements for proper disposal of electronic equipment, including hard drives, USB drives, CD-ROMs and other storage media which may contain various kinds of company data, some of which may be considered sensitive.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-21',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:10',
                'modified' => '2017-04-10 13:28:10',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '23',
                'index' => 'Information Logging Standard',
                'short_description' => 'Defines the specific requirements for information systems to generate appropriate audit logs that will integrate with an enterprise\'s log management function.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-22',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '24',
                'index' => 'Lab Security Policy',
                'short_description' => 'Defines requirements for labs (both internal and DMZ) to ensure that confidential information and technologies are not compromised, and that production services and interests of the organization are protected from lab activities.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-23',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '25',
                'index' => 'Server Security Policy',
                'short_description' => 'Defines standards for minimal security configuration for servers inside the organization\'s production network, or used in a production capacity.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-24',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '26',
                'index' => 'Software Installation Policy',
                'short_description' => 'Defines the requirements around installation of third party software on company owned devices.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-25',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '27',
                'index' => 'Workstation Security (For HIPAA) Policy',
                'short_description' => 'Defines the requirements to ensure the the HIPAA Security Rule âWorkstation Securityâ Standard 164.310(c) can be met.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/server-security#database-credentials-policy',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-26',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '28',
                'index' => 'Web Application Security Policy',
                'short_description' => 'Defines the requirement for completing a web application security assessment and guidelines for completing the assessment.',
                'description' => NULL,
                'url' => 'https://www.sans.org/security-resources/policies/application-security#web-application-security-policy',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1',
                'published_date' => '2015-11-30',
                'next_review_date' => '2018-01-27',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 13:28:11',
                'modified' => '2017-04-10 13:28:11',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '29',
                'index' => 'Information Security Policy',
                'short_description' => 'Our risk policy that describes overall governance, risk practices, Etc.',
                'description' => '',
                'url' => '',
                'use_attachments' => '1',
                'document_type' => 'policy',
                'version' => '4.5',
                'published_date' => '2017-04-10',
                'next_review_date' => '2017-06-22',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '2',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:15:38',
                'modified' => '2017-04-10 14:15:38',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '30',
                'index' => 'Network Security Policy',
                'short_description' => '',
                'description' => '',
                'url' => 'https://policies/version/1.3',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1.3',
                'published_date' => '2017-04-10',
                'next_review_date' => '2017-09-29',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '3',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:23:54',
                'modified' => '2017-04-10 14:23:54',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '31',
                'index' => 'Network Diagrams',
                'short_description' => '',
                'description' => '',
                'url' => 'https://policies/version/17',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1.5',
                'published_date' => '2017-04-10',
                'next_review_date' => '2017-04-30',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '2',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-10 14:29:23',
                'modified' => '2017-04-10 14:29:23',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '32',
                'index' => 'Governance Policy',
                'short_description' => 'This document describes the standards, guidelines and processes that govern Acme information Security Program.',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '2.11',
                'published_date' => '2016-02-29',
                'next_review_date' => '2017-08-31',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:55',
                'modified' => '2017-04-11 12:43:55',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '33',
                'index' => 'HR Policy',
                'short_description' => 'Describes the various security mechanisms utilized to ensure a controlled and systematic management of employees',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '2.4',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-08-22',
                'permission' => 'logged',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:55',
                'modified' => '2017-04-11 12:43:55',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '34',
                'index' => 'Access Management',
                'short_description' => 'Control access to information, information processing facilities, and business processes.',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '3.4',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-08-30',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '35',
                'index' => 'Physical Security',
                'short_description' => 'Prevent unauthorized physical access, damage, and interference to the organizationâ€™s premises and information.',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '3.4',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-08-21',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '36',
                'index' => 'IT System Policy',
                'short_description' => 'Ensure the correct and secure operation of information the information processing facilities.',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '3.5',
                'published_date' => '2015-11-30',
                'next_review_date' => '2017-08-30',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '37',
                'index' => 'Network Hardening Standards',
                'short_description' => 'This document describes the technical standards implemented and monitored across all critical UNIX productive related operating systems.',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '3.5',
                'published_date' => '2016-03-11',
                'next_review_date' => '2017-08-30',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '38',
                'index' => 'OS Hardening Standards',
                'short_description' => 'This document describes the technical standards implemented and monitored across all critical UNIX productive related operating systems.',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1.4',
                'published_date' => '2016-03-11',
                'next_review_date' => '2017-11-07',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '39',
                'index' => 'Datacenter Policies',
                'short_description' => 'Provides policies and procedures to govern the arrangement, continuity, operation and safety aspects of the physical spaces where tech equipment sits.',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1.1',
                'published_date' => '2014-06-16',
                'next_review_date' => '2017-05-31',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '40',
                'index' => 'Active Directory Standards',
                'short_description' => 'This document describes the technical standards implemented and monitored across all Active Directory productive related operating systems.',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'standard',
                'version' => '1.2',
                'published_date' => '2015-10-23',
                'next_review_date' => '2017-10-24',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '41',
                'index' => 'Change Management Process',
                'short_description' => 'This document describes the high level processes that govern changes in the infrastructure managed by Acme infrastructure teams.',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'procedure',
                'version' => '1.6',
                'published_date' => '2015-07-06',
                'next_review_date' => '2017-07-10',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
            [
                'id' => '42',
                'index' => 'Encryption Key Management',
                'short_description' => 'The creation, management and disposal of keys are documented in this document.',
                'description' => NULL,
                'url' => 'https://policies.com/template',
                'use_attachments' => '2',
                'document_type' => 'policy',
                'version' => '1.1',
                'published_date' => '2014-09-15',
                'next_review_date' => '2017-11-13',
                'permission' => 'public',
                'ldap_connector_id' => NULL,
                'asset_label_id' => NULL,
                'status' => '1',
                'expired_reviews' => '0',
                'author_id' => '1',
                'hash' => NULL,
                'workflow_owner_id' => '1',
                'workflow_status' => '4',
                'created' => '2017-04-11 12:43:56',
                'modified' => '2017-04-11 12:43:56',
                'deleted' => '0',
                'deleted_date' => NULL,
            ],
        ];

        $table = $this->table('security_policies');
        $table->insert($data)->save();
    }
}
