<?php
use Phinx\Seed\AbstractSeed;

/**
 * StatusTrigger seed.
 */
class StatusTriggerSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'model' => 'SecurityPolicy',
                'foreign_key' => '1',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '2',
                'model' => 'SecurityPolicy',
                'foreign_key' => '2',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '3',
                'model' => 'SecurityPolicy',
                'foreign_key' => '3',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '4',
                'model' => 'SecurityPolicy',
                'foreign_key' => '4',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '5',
                'model' => 'SecurityPolicy',
                'foreign_key' => '5',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '6',
                'model' => 'SecurityPolicy',
                'foreign_key' => '6',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '7',
                'model' => 'SecurityPolicy',
                'foreign_key' => '7',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '8',
                'model' => 'SecurityPolicy',
                'foreign_key' => '8',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '9',
                'model' => 'SecurityPolicy',
                'foreign_key' => '9',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '10',
                'model' => 'SecurityPolicy',
                'foreign_key' => '10',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '11',
                'model' => 'SecurityPolicy',
                'foreign_key' => '11',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '12',
                'model' => 'SecurityPolicy',
                'foreign_key' => '12',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '13',
                'model' => 'SecurityPolicy',
                'foreign_key' => '13',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '14',
                'model' => 'SecurityPolicy',
                'foreign_key' => '14',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '15',
                'model' => 'SecurityPolicy',
                'foreign_key' => '15',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '16',
                'model' => 'SecurityPolicy',
                'foreign_key' => '16',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '17',
                'model' => 'SecurityPolicy',
                'foreign_key' => '17',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '18',
                'model' => 'SecurityPolicy',
                'foreign_key' => '18',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '19',
                'model' => 'SecurityPolicy',
                'foreign_key' => '19',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '20',
                'model' => 'SecurityPolicy',
                'foreign_key' => '20',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '21',
                'model' => 'SecurityPolicy',
                'foreign_key' => '21',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '22',
                'model' => 'SecurityPolicy',
                'foreign_key' => '22',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '23',
                'model' => 'SecurityPolicy',
                'foreign_key' => '23',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:11',
            ],
            [
                'id' => '24',
                'model' => 'SecurityPolicy',
                'foreign_key' => '24',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:11',
            ],
            [
                'id' => '25',
                'model' => 'SecurityPolicy',
                'foreign_key' => '25',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:11',
            ],
            [
                'id' => '26',
                'model' => 'SecurityPolicy',
                'foreign_key' => '26',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:11',
            ],
            [
                'id' => '27',
                'model' => 'SecurityPolicy',
                'foreign_key' => '27',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:11',
            ],
            [
                'id' => '28',
                'model' => 'SecurityPolicy',
                'foreign_key' => '28',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 13:28:11',
            ],
            [
                'id' => '29',
                'model' => 'SecurityService',
                'foreign_key' => '1',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '30',
                'model' => 'SecurityService',
                'foreign_key' => '1',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '31',
                'model' => 'SecurityService',
                'foreign_key' => '1',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '32',
                'model' => 'SecurityService',
                'foreign_key' => '1',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '33',
                'model' => 'SecurityService',
                'foreign_key' => '1',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '34',
                'model' => 'SecurityService',
                'foreign_key' => '1',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '35',
                'model' => 'SecurityService',
                'foreign_key' => '2',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '36',
                'model' => 'SecurityService',
                'foreign_key' => '2',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '37',
                'model' => 'SecurityService',
                'foreign_key' => '2',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '38',
                'model' => 'SecurityService',
                'foreign_key' => '2',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '39',
                'model' => 'SecurityService',
                'foreign_key' => '2',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '40',
                'model' => 'SecurityService',
                'foreign_key' => '2',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '41',
                'model' => 'SecurityService',
                'foreign_key' => '2',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '42',
                'model' => 'SecurityService',
                'foreign_key' => '3',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '43',
                'model' => 'SecurityService',
                'foreign_key' => '3',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '44',
                'model' => 'SecurityService',
                'foreign_key' => '3',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '45',
                'model' => 'SecurityService',
                'foreign_key' => '3',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '46',
                'model' => 'SecurityService',
                'foreign_key' => '3',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '47',
                'model' => 'SecurityService',
                'foreign_key' => '3',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '48',
                'model' => 'SecurityService',
                'foreign_key' => '4',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '49',
                'model' => 'SecurityService',
                'foreign_key' => '4',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '50',
                'model' => 'SecurityService',
                'foreign_key' => '4',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '51',
                'model' => 'SecurityService',
                'foreign_key' => '4',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '52',
                'model' => 'SecurityService',
                'foreign_key' => '4',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '53',
                'model' => 'SecurityService',
                'foreign_key' => '5',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '54',
                'model' => 'SecurityService',
                'foreign_key' => '5',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '55',
                'model' => 'SecurityService',
                'foreign_key' => '5',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '56',
                'model' => 'SecurityService',
                'foreign_key' => '5',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '57',
                'model' => 'SecurityService',
                'foreign_key' => '5',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '58',
                'model' => 'SecurityService',
                'foreign_key' => '6',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '59',
                'model' => 'SecurityService',
                'foreign_key' => '6',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '60',
                'model' => 'SecurityService',
                'foreign_key' => '6',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '61',
                'model' => 'SecurityService',
                'foreign_key' => '6',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '62',
                'model' => 'SecurityService',
                'foreign_key' => '7',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '63',
                'model' => 'SecurityService',
                'foreign_key' => '7',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '64',
                'model' => 'SecurityService',
                'foreign_key' => '7',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '65',
                'model' => 'SecurityService',
                'foreign_key' => '7',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '66',
                'model' => 'SecurityService',
                'foreign_key' => '7',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '67',
                'model' => 'SecurityService',
                'foreign_key' => '7',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '68',
                'model' => 'SecurityService',
                'foreign_key' => '8',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '69',
                'model' => 'SecurityService',
                'foreign_key' => '8',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '70',
                'model' => 'SecurityService',
                'foreign_key' => '8',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '71',
                'model' => 'SecurityService',
                'foreign_key' => '8',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '72',
                'model' => 'SecurityService',
                'foreign_key' => '8',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '73',
                'model' => 'SecurityService',
                'foreign_key' => '8',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '74',
                'model' => 'SecurityService',
                'foreign_key' => '9',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '75',
                'model' => 'SecurityService',
                'foreign_key' => '9',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '76',
                'model' => 'SecurityService',
                'foreign_key' => '9',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '77',
                'model' => 'SecurityService',
                'foreign_key' => '9',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '78',
                'model' => 'SecurityService',
                'foreign_key' => '10',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '79',
                'model' => 'SecurityService',
                'foreign_key' => '10',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '80',
                'model' => 'SecurityService',
                'foreign_key' => '10',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '81',
                'model' => 'SecurityService',
                'foreign_key' => '10',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:37',
            ],
            [
                'id' => '82',
                'model' => 'SecurityService',
                'foreign_key' => '11',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '83',
                'model' => 'SecurityService',
                'foreign_key' => '11',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '84',
                'model' => 'SecurityService',
                'foreign_key' => '11',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '85',
                'model' => 'SecurityService',
                'foreign_key' => '11',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '86',
                'model' => 'SecurityService',
                'foreign_key' => '12',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '87',
                'model' => 'SecurityService',
                'foreign_key' => '12',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '88',
                'model' => 'SecurityService',
                'foreign_key' => '12',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '89',
                'model' => 'SecurityService',
                'foreign_key' => '12',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '90',
                'model' => 'SecurityService',
                'foreign_key' => '13',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '91',
                'model' => 'SecurityService',
                'foreign_key' => '13',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '92',
                'model' => 'SecurityService',
                'foreign_key' => '13',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '93',
                'model' => 'SecurityService',
                'foreign_key' => '13',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '94',
                'model' => 'SecurityService',
                'foreign_key' => '14',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '95',
                'model' => 'SecurityService',
                'foreign_key' => '14',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '96',
                'model' => 'SecurityService',
                'foreign_key' => '14',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '97',
                'model' => 'SecurityService',
                'foreign_key' => '14',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '98',
                'model' => 'SecurityService',
                'foreign_key' => '14',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '99',
                'model' => 'SecurityService',
                'foreign_key' => '14',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '100',
                'model' => 'SecurityService',
                'foreign_key' => '15',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '101',
                'model' => 'SecurityService',
                'foreign_key' => '15',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '102',
                'model' => 'SecurityService',
                'foreign_key' => '15',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '103',
                'model' => 'SecurityService',
                'foreign_key' => '15',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '104',
                'model' => 'SecurityService',
                'foreign_key' => '16',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '105',
                'model' => 'SecurityService',
                'foreign_key' => '16',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '106',
                'model' => 'SecurityService',
                'foreign_key' => '16',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '107',
                'model' => 'SecurityService',
                'foreign_key' => '16',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '108',
                'model' => 'SecurityService',
                'foreign_key' => '16',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '109',
                'model' => 'SecurityService',
                'foreign_key' => '16',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '110',
                'model' => 'SecurityService',
                'foreign_key' => '17',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '111',
                'model' => 'SecurityService',
                'foreign_key' => '17',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '112',
                'model' => 'SecurityService',
                'foreign_key' => '17',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '113',
                'model' => 'SecurityService',
                'foreign_key' => '17',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '114',
                'model' => 'SecurityService',
                'foreign_key' => '17',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '115',
                'model' => 'SecurityService',
                'foreign_key' => '17',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '116',
                'model' => 'SecurityService',
                'foreign_key' => '18',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '117',
                'model' => 'SecurityService',
                'foreign_key' => '18',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '118',
                'model' => 'SecurityService',
                'foreign_key' => '18',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '119',
                'model' => 'SecurityService',
                'foreign_key' => '18',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '120',
                'model' => 'SecurityService',
                'foreign_key' => '19',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '121',
                'model' => 'SecurityService',
                'foreign_key' => '19',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '122',
                'model' => 'SecurityService',
                'foreign_key' => '19',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '123',
                'model' => 'SecurityService',
                'foreign_key' => '19',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '124',
                'model' => 'SecurityService',
                'foreign_key' => '19',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '125',
                'model' => 'SecurityService',
                'foreign_key' => '19',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '126',
                'model' => 'SecurityService',
                'foreign_key' => '20',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '127',
                'model' => 'SecurityService',
                'foreign_key' => '20',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '128',
                'model' => 'SecurityService',
                'foreign_key' => '20',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '129',
                'model' => 'SecurityService',
                'foreign_key' => '20',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '130',
                'model' => 'SecurityService',
                'foreign_key' => '20',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '131',
                'model' => 'SecurityService',
                'foreign_key' => '20',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '132',
                'model' => 'SecurityService',
                'foreign_key' => '21',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '133',
                'model' => 'SecurityService',
                'foreign_key' => '21',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '134',
                'model' => 'SecurityService',
                'foreign_key' => '21',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '135',
                'model' => 'SecurityService',
                'foreign_key' => '21',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '136',
                'model' => 'SecurityService',
                'foreign_key' => '22',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '137',
                'model' => 'SecurityService',
                'foreign_key' => '22',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '138',
                'model' => 'SecurityService',
                'foreign_key' => '22',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '139',
                'model' => 'SecurityService',
                'foreign_key' => '22',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '140',
                'model' => 'SecurityService',
                'foreign_key' => '22',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '141',
                'model' => 'SecurityService',
                'foreign_key' => '22',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '142',
                'model' => 'SecurityService',
                'foreign_key' => '23',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '143',
                'model' => 'SecurityService',
                'foreign_key' => '23',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:38',
            ],
            [
                'id' => '144',
                'model' => 'SecurityService',
                'foreign_key' => '23',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '145',
                'model' => 'SecurityService',
                'foreign_key' => '23',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '146',
                'model' => 'SecurityService',
                'foreign_key' => '23',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '147',
                'model' => 'SecurityService',
                'foreign_key' => '23',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '148',
                'model' => 'SecurityService',
                'foreign_key' => '24',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '149',
                'model' => 'SecurityService',
                'foreign_key' => '24',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '150',
                'model' => 'SecurityService',
                'foreign_key' => '24',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '151',
                'model' => 'SecurityService',
                'foreign_key' => '24',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '152',
                'model' => 'SecurityService',
                'foreign_key' => '25',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '153',
                'model' => 'SecurityService',
                'foreign_key' => '25',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '154',
                'model' => 'SecurityService',
                'foreign_key' => '25',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '155',
                'model' => 'SecurityService',
                'foreign_key' => '25',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-10 13:28:39',
            ],
            [
                'id' => '156',
                'model' => 'SecurityPolicy',
                'foreign_key' => '29',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 14:15:38',
            ],
            [
                'id' => '157',
                'model' => 'ComplianceManagement',
                'foreign_key' => '1',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:19:19',
            ],
            [
                'id' => '158',
                'model' => 'ComplianceManagement',
                'foreign_key' => '2',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:20:02',
            ],
            [
                'id' => '159',
                'model' => 'ComplianceManagement',
                'foreign_key' => '3',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:20:42',
            ],
            [
                'id' => '160',
                'model' => 'ComplianceManagement',
                'foreign_key' => '4',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:20:59',
            ],
            [
                'id' => '161',
                'model' => 'ComplianceManagement',
                'foreign_key' => '5',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:21:28',
            ],
            [
                'id' => '162',
                'model' => 'ComplianceManagement',
                'foreign_key' => '6',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:21:38',
            ],
            [
                'id' => '163',
                'model' => 'ComplianceManagement',
                'foreign_key' => '7',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:21:55',
            ],
            [
                'id' => '164',
                'model' => 'ComplianceManagement',
                'foreign_key' => '8',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:22:32',
            ],
            [
                'id' => '165',
                'model' => 'ComplianceManagement',
                'foreign_key' => '9',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:22:53',
            ],
            [
                'id' => '166',
                'model' => 'SecurityPolicy',
                'foreign_key' => '30',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 14:23:54',
            ],
            [
                'id' => '167',
                'model' => 'ComplianceManagement',
                'foreign_key' => '10',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:24:17',
            ],
            [
                'id' => '168',
                'model' => 'ComplianceManagement',
                'foreign_key' => '11',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:25:09',
            ],
            [
                'id' => '169',
                'model' => 'ComplianceManagement',
                'foreign_key' => '12',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:25:40',
            ],
            [
                'id' => '170',
                'model' => 'ComplianceManagement',
                'foreign_key' => '13',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:26:18',
            ],
            [
                'id' => '171',
                'model' => 'ComplianceManagement',
                'foreign_key' => '14',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:27:24',
            ],
            [
                'id' => '172',
                'model' => 'ComplianceManagement',
                'foreign_key' => '15',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:28:09',
            ],
            [
                'id' => '173',
                'model' => 'ComplianceManagement',
                'foreign_key' => '15',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '3',
                'created' => '2017-04-10 14:28:22',
            ],
            [
                'id' => '174',
                'model' => 'SecurityPolicy',
                'foreign_key' => '31',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-10 14:29:23',
            ],
            [
                'id' => '175',
                'model' => 'ComplianceManagement',
                'foreign_key' => '16',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:30:12',
            ],
            [
                'id' => '176',
                'model' => 'ComplianceManagement',
                'foreign_key' => '17',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:30:37',
            ],
            [
                'id' => '177',
                'model' => 'ComplianceManagement',
                'foreign_key' => '18',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:30:57',
            ],
            [
                'id' => '178',
                'model' => 'ComplianceManagement',
                'foreign_key' => '19',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:32:51',
            ],
            [
                'id' => '179',
                'model' => 'ComplianceManagement',
                'foreign_key' => '20',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:33:05',
            ],
            [
                'id' => '180',
                'model' => 'ComplianceManagement',
                'foreign_key' => '21',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:33:25',
            ],
            [
                'id' => '181',
                'model' => 'ComplianceManagement',
                'foreign_key' => '22',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:33:41',
            ],
            [
                'id' => '182',
                'model' => 'ComplianceManagement',
                'foreign_key' => '23',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:33:58',
            ],
            [
                'id' => '183',
                'model' => 'ComplianceManagement',
                'foreign_key' => '24',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:34:46',
            ],
            [
                'id' => '184',
                'model' => 'ComplianceManagement',
                'foreign_key' => '25',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:35:08',
            ],
            [
                'id' => '185',
                'model' => 'ComplianceManagement',
                'foreign_key' => '26',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:35:39',
            ],
            [
                'id' => '186',
                'model' => 'ComplianceManagement',
                'foreign_key' => '27',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:36:08',
            ],
            [
                'id' => '187',
                'model' => 'ComplianceManagement',
                'foreign_key' => '28',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:36:41',
            ],
            [
                'id' => '188',
                'model' => 'ComplianceManagement',
                'foreign_key' => '29',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:37:29',
            ],
            [
                'id' => '189',
                'model' => 'ComplianceManagement',
                'foreign_key' => '30',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:37:51',
            ],
            [
                'id' => '190',
                'model' => 'ComplianceManagement',
                'foreign_key' => '31',
                'config_name' => 'compliance_treatment_strategy_id',
                'column_name' => 'compliance_treatment_strategy_id',
                'value' => '1',
                'created' => '2017-04-10 14:42:02',
            ],
            [
                'id' => '191',
                'model' => 'Asset',
                'foreign_key' => '9',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-10 15:50:46',
            ],
            [
                'id' => '192',
                'model' => 'Asset',
                'foreign_key' => '9',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-10 15:50:46',
            ],
            [
                'id' => '193',
                'model' => 'Asset',
                'foreign_key' => '10',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-10 15:50:46',
            ],
            [
                'id' => '194',
                'model' => 'Asset',
                'foreign_key' => '10',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-10 15:50:46',
            ],
            [
                'id' => '195',
                'model' => 'Asset',
                'foreign_key' => '11',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-10 15:50:46',
            ],
            [
                'id' => '196',
                'model' => 'Asset',
                'foreign_key' => '11',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-10 15:50:46',
            ],
            [
                'id' => '197',
                'model' => 'Asset',
                'foreign_key' => '12',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-10 15:50:46',
            ],
            [
                'id' => '198',
                'model' => 'Asset',
                'foreign_key' => '12',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-10 15:50:46',
            ],
            [
                'id' => '199',
                'model' => 'Asset',
                'foreign_key' => '13',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-10 15:50:46',
            ],
            [
                'id' => '200',
                'model' => 'Asset',
                'foreign_key' => '13',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-10 15:50:46',
            ],
            [
                'id' => '201',
                'model' => 'Asset',
                'foreign_key' => '9',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '0',
                'created' => '2017-04-10 15:53:30',
            ],
            [
                'id' => '202',
                'model' => 'Asset',
                'foreign_key' => '10',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '0',
                'created' => '2017-04-10 15:53:41',
            ],
            [
                'id' => '203',
                'model' => 'Asset',
                'foreign_key' => '11',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '0',
                'created' => '2017-04-10 15:53:51',
            ],
            [
                'id' => '204',
                'model' => 'Asset',
                'foreign_key' => '12',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '0',
                'created' => '2017-04-10 15:54:11',
            ],
            [
                'id' => '205',
                'model' => 'SecurityPolicy',
                'foreign_key' => '32',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:55',
            ],
            [
                'id' => '206',
                'model' => 'SecurityPolicy',
                'foreign_key' => '33',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '207',
                'model' => 'SecurityPolicy',
                'foreign_key' => '34',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '208',
                'model' => 'SecurityPolicy',
                'foreign_key' => '35',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '209',
                'model' => 'SecurityPolicy',
                'foreign_key' => '36',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '210',
                'model' => 'SecurityPolicy',
                'foreign_key' => '37',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '211',
                'model' => 'SecurityPolicy',
                'foreign_key' => '38',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '212',
                'model' => 'SecurityPolicy',
                'foreign_key' => '39',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '213',
                'model' => 'SecurityPolicy',
                'foreign_key' => '40',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '214',
                'model' => 'SecurityPolicy',
                'foreign_key' => '41',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '215',
                'model' => 'SecurityPolicy',
                'foreign_key' => '42',
                'config_name' => 'status',
                'column_name' => 'status',
                'value' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '216',
                'model' => 'SecurityService',
                'foreign_key' => '2',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '0',
                'created' => '2017-04-11 12:47:04',
            ],
            [
                'id' => '217',
                'model' => 'SecurityService',
                'foreign_key' => '2',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-11 12:47:36',
            ],
            [
                'id' => '218',
                'model' => 'SecurityService',
                'foreign_key' => '4',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '0',
                'created' => '2017-04-11 12:48:59',
            ],
            [
                'id' => '219',
                'model' => 'SecurityService',
                'foreign_key' => '7',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '0',
                'created' => '2017-04-11 12:49:54',
            ],
            [
                'id' => '220',
                'model' => 'SecurityService',
                'foreign_key' => '8',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '0',
                'created' => '2017-04-11 12:51:24',
            ],
            [
                'id' => '221',
                'model' => 'SecurityService',
                'foreign_key' => '26',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-11 13:05:02',
            ],
            [
                'id' => '222',
                'model' => 'SecurityService',
                'foreign_key' => '26',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-11 13:05:02',
            ],
            [
                'id' => '223',
                'model' => 'SecurityService',
                'foreign_key' => '26',
                'config_name' => 'maintenancesLastMissing',
                'column_name' => 'maintenances_last_missing',
                'value' => '0',
                'created' => '2017-04-11 13:05:02',
            ],
            [
                'id' => '224',
                'model' => 'SecurityService',
                'foreign_key' => '26',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-11 13:05:02',
            ],
            [
                'id' => '225',
                'model' => 'Risk',
                'foreign_key' => '1',
                'config_name' => 'riskAboveAppetite',
                'column_name' => 'risk_above_appetite',
                'value' => '1',
                'created' => '2017-04-11 13:05:33',
            ],
            [
                'id' => '226',
                'model' => 'Risk',
                'foreign_key' => '2',
                'config_name' => 'riskAboveAppetite',
                'column_name' => 'risk_above_appetite',
                'value' => '1',
                'created' => '2017-04-11 13:07:37',
            ],
            [
                'id' => '227',
                'model' => 'SecurityIncident',
                'foreign_key' => '1',
                'config_name' => 'status',
                'column_name' => 'security_incident_status_id',
                'value' => '2',
                'created' => '2017-04-11 13:10:29',
            ],
            [
                'id' => '228',
                'model' => 'SecurityIncident',
                'foreign_key' => '1',
                'config_name' => 'lifecycleIncomplete',
                'column_name' => 'lifecycle_incomplete',
                'value' => '1',
                'created' => '2017-04-11 13:10:29',
            ],
            [
                'id' => '229',
                'model' => 'SecurityIncident',
                'foreign_key' => '1',
                'config_name' => 'lifecycleIncomplete',
                'column_name' => 'lifecycle_incomplete',
                'value' => '0',
                'created' => '2017-04-11 13:10:49',
            ],
            [
                'id' => '230',
                'model' => 'SecurityIncident',
                'foreign_key' => '1',
                'config_name' => 'status',
                'column_name' => 'security_incident_status_id',
                'value' => '3',
                'created' => '2017-04-11 13:10:49',
            ],
            [
                'id' => '231',
                'model' => 'SecurityIncident',
                'foreign_key' => '2',
                'config_name' => 'status',
                'column_name' => 'security_incident_status_id',
                'value' => '2',
                'created' => '2017-04-11 13:12:25',
            ],
            [
                'id' => '232',
                'model' => 'SecurityIncident',
                'foreign_key' => '2',
                'config_name' => 'lifecycleIncomplete',
                'column_name' => 'lifecycle_incomplete',
                'value' => '1',
                'created' => '2017-04-11 13:12:25',
            ],
            [
                'id' => '233',
                'model' => 'SecurityService',
                'foreign_key' => '2',
                'config_name' => 'ongoingCorrectiveActions',
                'column_name' => 'ongoing_corrective_actions',
                'value' => '1',
                'created' => '2017-04-11 16:56:38',
            ],
            [
                'id' => '234',
                'model' => 'SecurityPolicy',
                'foreign_key' => '3',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-12 07:47:44',
            ],
            [
                'id' => '235',
                'model' => 'SecurityPolicy',
                'foreign_key' => '6',
                'config_name' => 'expiredReviews',
                'column_name' => 'expired_reviews',
                'value' => '1',
                'created' => '2017-04-12 07:47:44',
            ],
            [
                'id' => '236',
                'model' => 'SecurityService',
                'foreign_key' => '9',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-12 07:47:44',
            ],
            [
                'id' => '237',
                'model' => 'BusinessContinuityPlan',
                'foreign_key' => '1',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-12 12:05:22',
            ],
            [
                'id' => '238',
                'model' => 'BusinessContinuityPlan',
                'foreign_key' => '1',
                'config_name' => 'auditsLastFailed',
                'column_name' => 'audits_last_passed',
                'value' => '1',
                'created' => '2017-04-12 12:05:22',
            ],
            [
                'id' => '239',
                'model' => 'BusinessContinuityPlan',
                'foreign_key' => '1',
                'config_name' => 'status',
                'column_name' => 'security_service_type_id',
                'value' => '4',
                'created' => '2017-04-12 12:05:22',
            ],
            [
                'id' => '240',
                'model' => 'SecurityService',
                'foreign_key' => '25',
                'config_name' => 'auditsLastMissing',
                'column_name' => 'audits_last_missing',
                'value' => '1',
                'created' => '2017-04-16 00:00:07',
            ],
        ];

        $table = $this->table('status_triggers');
        $table->insert($data)->save();
    }
}
