<?php
use Phinx\Seed\AbstractSeed;

/**
 * Tag seed.
 */
class TagSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'model' => 'SecurityPolicy',
                'foreign_key' => '1',
                'title' => 'Encryption ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '2',
                'model' => 'SecurityPolicy',
                'foreign_key' => '1',
                'title' => ' Access Management',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '3',
                'model' => 'SecurityPolicy',
                'foreign_key' => '2',
                'title' => 'Equipment Use',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '4',
                'model' => 'SecurityPolicy',
                'foreign_key' => '3',
                'title' => 'Physical Security ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '5',
                'model' => 'SecurityPolicy',
                'foreign_key' => '3',
                'title' => ' Clean Desk',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '6',
                'model' => 'SecurityPolicy',
                'foreign_key' => '4',
                'title' => 'Incident Management',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '7',
                'model' => 'SecurityPolicy',
                'foreign_key' => '5',
                'title' => 'DRP ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '8',
                'model' => 'SecurityPolicy',
                'foreign_key' => '5',
                'title' => ' BCM',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '9',
                'model' => 'SecurityPolicy',
                'foreign_key' => '7',
                'title' => 'Email',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '10',
                'model' => 'SecurityPolicy',
                'foreign_key' => '8',
                'title' => 'Privacy ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '11',
                'model' => 'SecurityPolicy',
                'foreign_key' => '8',
                'title' => ' Ethics',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '12',
                'model' => 'SecurityPolicy',
                'foreign_key' => '9',
                'title' => 'DRP ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '13',
                'model' => 'SecurityPolicy',
                'foreign_key' => '9',
                'title' => ' BCM',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '14',
                'model' => 'SecurityPolicy',
                'foreign_key' => '10',
                'title' => 'Password',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '15',
                'model' => 'SecurityPolicy',
                'foreign_key' => '11',
                'title' => 'Password',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '16',
                'model' => 'SecurityPolicy',
                'foreign_key' => '12',
                'title' => 'DRP ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '17',
                'model' => 'SecurityPolicy',
                'foreign_key' => '12',
                'title' => ' BCM ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '18',
                'model' => 'SecurityPolicy',
                'foreign_key' => '12',
                'title' => ' Incident Management',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '19',
                'model' => 'SecurityPolicy',
                'foreign_key' => '13',
                'title' => 'Encryption',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '20',
                'model' => 'SecurityPolicy',
                'foreign_key' => '14',
                'title' => 'Procurement ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '21',
                'model' => 'SecurityPolicy',
                'foreign_key' => '14',
                'title' => ' Networks',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '22',
                'model' => 'SecurityPolicy',
                'foreign_key' => '15',
                'title' => 'Wireless',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '23',
                'model' => 'SecurityPolicy',
                'foreign_key' => '16',
                'title' => 'Access ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '24',
                'model' => 'SecurityPolicy',
                'foreign_key' => '16',
                'title' => ' Network',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '25',
                'model' => 'SecurityPolicy',
                'foreign_key' => '17',
                'title' => 'Access ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '26',
                'model' => 'SecurityPolicy',
                'foreign_key' => '17',
                'title' => ' Remote Connections',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '27',
                'model' => 'SecurityPolicy',
                'foreign_key' => '18',
                'title' => 'Network ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '28',
                'model' => 'SecurityPolicy',
                'foreign_key' => '18',
                'title' => ' Standard Configs',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '29',
                'model' => 'SecurityPolicy',
                'foreign_key' => '19',
                'title' => 'Wireless',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '30',
                'model' => 'SecurityPolicy',
                'foreign_key' => '20',
                'title' => 'Wireless',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '31',
                'model' => 'SecurityPolicy',
                'foreign_key' => '21',
                'title' => 'Datacenter ',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '32',
                'model' => 'SecurityPolicy',
                'foreign_key' => '21',
                'title' => ' Access',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:10',
            ],
            [
                'id' => '33',
                'model' => 'SecurityPolicy',
                'foreign_key' => '23',
                'title' => 'Logging',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:11',
            ],
            [
                'id' => '34',
                'model' => 'SecurityPolicy',
                'foreign_key' => '24',
                'title' => 'Lab',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:11',
            ],
            [
                'id' => '35',
                'model' => 'SecurityPolicy',
                'foreign_key' => '25',
                'title' => 'Standard Configs',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:11',
            ],
            [
                'id' => '36',
                'model' => 'SecurityPolicy',
                'foreign_key' => '26',
                'title' => 'Software',
                'user_id' => '1',
                'created' => '2017-04-10 13:28:11',
            ],
            [
                'id' => '37',
                'model' => 'SecurityPolicy',
                'foreign_key' => '29',
                'title' => 'Security',
                'user_id' => '1',
                'created' => '2017-04-10 14:15:38',
            ],
            [
                'id' => '38',
                'model' => 'SecurityPolicy',
                'foreign_key' => '29',
                'title' => 'Governance',
                'user_id' => '1',
                'created' => '2017-04-10 14:15:38',
            ],
            [
                'id' => '39',
                'model' => 'ComplianceException',
                'foreign_key' => '1',
                'title' => 'Disciplinary',
                'user_id' => '1',
                'created' => '2017-04-10 14:41:54',
            ],
            [
                'id' => '40',
                'model' => 'SecurityPolicy',
                'foreign_key' => '32',
                'title' => 'GRC',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:55',
            ],
            [
                'id' => '41',
                'model' => 'SecurityPolicy',
                'foreign_key' => '33',
                'title' => 'Human Resources',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:55',
            ],
            [
                'id' => '42',
                'model' => 'SecurityPolicy',
                'foreign_key' => '34',
                'title' => 'Access Management',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '43',
                'model' => 'SecurityPolicy',
                'foreign_key' => '35',
                'title' => 'Physical Security',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '44',
                'model' => 'SecurityPolicy',
                'foreign_key' => '36',
                'title' => 'System Security',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '45',
                'model' => 'SecurityPolicy',
                'foreign_key' => '37',
                'title' => 'Network Security',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '46',
                'model' => 'SecurityPolicy',
                'foreign_key' => '38',
                'title' => 'System Security',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '47',
                'model' => 'SecurityPolicy',
                'foreign_key' => '39',
                'title' => 'Physical Security',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '48',
                'model' => 'SecurityPolicy',
                'foreign_key' => '40',
                'title' => 'System Security',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '49',
                'model' => 'SecurityPolicy',
                'foreign_key' => '41',
                'title' => 'Operations Security',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '50',
                'model' => 'SecurityPolicy',
                'foreign_key' => '42',
                'title' => 'System Security',
                'user_id' => '1',
                'created' => '2017-04-11 12:43:56',
            ],
            [
                'id' => '51',
                'model' => 'Project',
                'foreign_key' => '1',
                'title' => 'IDS',
                'user_id' => '1',
                'created' => '2017-04-11 13:14:34',
            ],
            [
                'id' => '52',
                'model' => 'Project',
                'foreign_key' => '1',
                'title' => 'Snort',
                'user_id' => '1',
                'created' => '2017-04-11 13:14:34',
            ],
        ];

        $table = $this->table('tags');
        $table->insert($data)->save();
    }
}
