<?php
use Phinx\Seed\AbstractSeed;

/**
 * ThirdPartyOvertimeGraph seed.
 */
class ThirdPartyOvertimeGraphSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'third_party_id' => '2',
                'no_controls' => '8',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '92',
                'timestamp' => '1491983265',
                'created' => '2017-04-12 07:47:45',
            ],
            [
                'id' => '2',
                'third_party_id' => '3',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '99',
                'timestamp' => '1491983265',
                'created' => '2017-04-12 07:47:45',
            ],
            [
                'id' => '3',
                'third_party_id' => '4',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '98',
                'timestamp' => '1491983265',
                'created' => '2017-04-12 07:47:45',
            ],
            [
                'id' => '4',
                'third_party_id' => '2',
                'no_controls' => '8',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '92',
                'timestamp' => '1492041614',
                'created' => '2017-04-13 00:00:14',
            ],
            [
                'id' => '5',
                'third_party_id' => '3',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '99',
                'timestamp' => '1492041614',
                'created' => '2017-04-13 00:00:14',
            ],
            [
                'id' => '6',
                'third_party_id' => '4',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '98',
                'timestamp' => '1492041614',
                'created' => '2017-04-13 00:00:14',
            ],
            [
                'id' => '7',
                'third_party_id' => '2',
                'no_controls' => '8',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '92',
                'timestamp' => '1492128015',
                'created' => '2017-04-14 00:00:15',
            ],
            [
                'id' => '8',
                'third_party_id' => '3',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '99',
                'timestamp' => '1492128015',
                'created' => '2017-04-14 00:00:15',
            ],
            [
                'id' => '9',
                'third_party_id' => '4',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '98',
                'timestamp' => '1492128015',
                'created' => '2017-04-14 00:00:15',
            ],
            [
                'id' => '10',
                'third_party_id' => '2',
                'no_controls' => '8',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '92',
                'timestamp' => '1492214417',
                'created' => '2017-04-15 00:00:17',
            ],
            [
                'id' => '11',
                'third_party_id' => '3',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '99',
                'timestamp' => '1492214417',
                'created' => '2017-04-15 00:00:17',
            ],
            [
                'id' => '12',
                'third_party_id' => '4',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '98',
                'timestamp' => '1492214417',
                'created' => '2017-04-15 00:00:17',
            ],
            [
                'id' => '13',
                'third_party_id' => '2',
                'no_controls' => '8',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '92',
                'timestamp' => '1492300814',
                'created' => '2017-04-16 00:00:14',
            ],
            [
                'id' => '14',
                'third_party_id' => '3',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '99',
                'timestamp' => '1492300814',
                'created' => '2017-04-16 00:00:14',
            ],
            [
                'id' => '15',
                'third_party_id' => '4',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '98',
                'timestamp' => '1492300814',
                'created' => '2017-04-16 00:00:14',
            ],
            [
                'id' => '16',
                'third_party_id' => '2',
                'no_controls' => '8',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '92',
                'timestamp' => '1492387218',
                'created' => '2017-04-17 00:00:18',
            ],
            [
                'id' => '17',
                'third_party_id' => '3',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '99',
                'timestamp' => '1492387218',
                'created' => '2017-04-17 00:00:18',
            ],
            [
                'id' => '18',
                'third_party_id' => '4',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '98',
                'timestamp' => '1492387218',
                'created' => '2017-04-17 00:00:18',
            ],
            [
                'id' => '19',
                'third_party_id' => '2',
                'no_controls' => '8',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '92',
                'timestamp' => '1492473615',
                'created' => '2017-04-18 00:00:15',
            ],
            [
                'id' => '20',
                'third_party_id' => '3',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '99',
                'timestamp' => '1492473615',
                'created' => '2017-04-18 00:00:15',
            ],
            [
                'id' => '21',
                'third_party_id' => '4',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '98',
                'timestamp' => '1492473615',
                'created' => '2017-04-18 00:00:15',
            ],
            [
                'id' => '22',
                'third_party_id' => '2',
                'no_controls' => '8',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '92',
                'timestamp' => '1492560015',
                'created' => '2017-04-19 00:00:15',
            ],
            [
                'id' => '23',
                'third_party_id' => '3',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '99',
                'timestamp' => '1492560015',
                'created' => '2017-04-19 00:00:15',
            ],
            [
                'id' => '24',
                'third_party_id' => '4',
                'no_controls' => '0',
                'failed_controls' => '100',
                'ok_controls' => '0',
                'average_effectiveness' => '98',
                'timestamp' => '1492560015',
                'created' => '2017-04-19 00:00:15',
            ],
        ];

        $table = $this->table('third_party_overtime_graphs');
        $table->insert($data)->save();
    }
}
