<?php
App::uses('AppModel', 'Model');

class OauthConnector extends AppModel
{
	public $displayField = 'name';

	const PROVIDER_GOOGLE = 'google';
	const STATUS_DISABLED = 0;
	const STATUS_ACTIVE = 1;

	protected $_appModelConfig = [
		'behaviors' => [
		],
		'elements' => [
		]
	];

	public $mapping = array(
		'titleColumn' => 'name',
		'logRecords' => true,
		'notificationSystem' => array('index'),
		'workflow' => false
	);

	public $actsAs = array(
		'Containable',
		'HtmlPurifier.HtmlPurifier' => array(
			'config' => 'Strict',
			'fields' => array(
				'name', 'client_id', 'client_secret', 'provider', 'status'
			)
		),
		'Comments.Comments',
		'Attachments.Attachments',
		'Widget.Widget',
		'AdvancedFilters.AdvancedFilters'
	);

	public $validate = [
		'name' => [
			'rule' => 'notBlank',
			'required' => true,
			'allowEmpty' => false,
			'message' => 'Name is required'
		],
		'client_id' => [
			'rule' => 'notBlank',
			'required' => true,
			'allowEmpty' => false,
			'message' => 'Client ID is required'
		],
		'client_secret' => [
			'rule' => 'notBlank',
			'required' => true,
			'allowEmpty' => false,
			'message' => 'Client Secret is required'
		],
		'provider' => [
			'rule' => 'notBlank',
			'required' => true,
			'allowEmpty' => false,
			'message' => 'You have to choose a provider'
		]
	];

	public $hasMany = array(
	);

	public $hasOne = array(
		'LdapAuthGoogleOauth' => array(
			'className' => 'LdapConnectorAuthentication',
			'foreignKey' => 'oauth_google_id'
		)
	);

	public function __construct($id = false, $table = null, $ds = null)
	{
		$this->label = __('OAuth Connectors');
		$this->_group = parent::SECTION_GROUP_SYSTEM;

		$this->fieldGroupData = [
			'default' => [
				'label' => __('General')
			]
		];

		$this->fieldData = [
			'name' => [
				'label' => __('Name'),
				'editable' => true,
				'description' => __('Name of this OAuth Connector'),
			],
			'client_id' => [
				'label' => __('Client ID'),
				'editable' => true,
				'description' => __('Client ID generated by an OAuth provider'),
			],
			'client_secret' => [
				'label' => __('Client Secret'),
				'editable' => true,
				'description' => __('Client Secret generated by an OAuth provider'),
			],
			'redirect_urls' => [
				'label' => __('Redirect URLs'),
				'editable' => true,
				'description' => __("These URLs are used for redirecting user back to eramba's portal after he have authenticated with provider. Copy these URLs to your provider's API Credentials"),
				'renderHelper' => ['OauthConnectors', 'redirectUrlsField']
			],
			'provider' => [
				'label' => __('Provider'),
				'editable' => true,
				'description' => __('Provider of OAuth.'),
				'empty' => __('Choose provider'),
				'options' => [$this, 'providers']
			],
			'status' => [
				'label' => __('Status'),
				'editable' => true,
				'description' => __('If the connector is disabled or enabled (is ready to be used across the system)'),
				'options' => [$this, 'getStatuses']
			]
		];

		parent::__construct($id, $table, $ds);
	}

	public function getAdvancedFilterConfig()
	{
		$advancedFilterConfig = $this->createAdvancedFilterConfig()
			->group('general', [
				'name' => __('General')
			])
				->nonFilterableField('id')
				->textField('name', [
					'showDefault' => true
				])
				->textField('client_id', [
					'showDefault' => true
				])
				->textField('client_secret', [
					'showDefault' => true
				])
				->selectField('provider', [$this, 'providers'], [
					'showDefault' => true
				])
				->selectField('status', [$this, 'statuses'], [
					'showDefault' => true
				]);

		$this->otherFilters($advancedFilterConfig);

		return $advancedFilterConfig->getConfiguration()->toArray();
	}

	public function getProviders() {
		return self::providers();
	}

	//
	// Possible providers
	public function providers($value = null) {
		$options = array(
			self::PROVIDER_GOOGLE => __('Google')
		);
		return parent::enum($value, $options);
	}

	public function getStatuses() {
		return self::statuses();
	}

	// possible statuses
	public static function statuses($value = null) {
		$options = array(
			self::STATUS_DISABLED => __('Disabled'),
			self::STATUS_ACTIVE => __('Active')
		);
		return parent::enum($value, $options);
	}

	public function beforeValidate($options = array()) {
		
		// Default validation
		$this->addListValidation('status', array_keys(self::statuses()));
		$this->addListValidation('provider', array_keys($this->providers()));

		$this->handleProviderValidation();

		return true;
	}

	private function handleProviderValidation() {
		if ($this->data['OauthConnector']['provider'] == self::PROVIDER_GOOGLE) {
			//
			// Preparation: when another providers will be added
		}
	}

	public function getActiveOauthData()
	{
		$data = $this->find('first', array(
			'conditions' => array(
				'LdapAuthGoogleOauth.oauth_google' => 1,
				'OauthConnector.status' => self::STATUS_ACTIVE,
				"`LdapAuthGoogleOauth`.`oauth_google_id`=`OauthConnector`.`id`"
			)
		));

		if (!empty($data)) {
			return array(
				'clientId' => $data['OauthConnector']['client_id'],
				'clientSecret' => $data['OauthConnector']['client_secret']
			);
		} else {
			return false;
		}
	}

	/**
	 * Restrict deletion if a Connector is still in use.
	 */
	public function beforeDelete($cascade = true)
	{
		return $this->prepareDelete($this->id);
	}

	public function prepareDelete($id)
	{
		$ret = true;

		if ($this->inUse($id)) {
			$ret = false;
			$this->customDeleteMessage = __('OAuth Connector cannot be deleted because is in use.');
		}
		
		return $ret;
	}

	/**
	 * Checks if an OAuth Connector is used in some part of the system.
	 */
	private function inUse($id)
	{
		$data = $this->find('first', array(
			'fields' => array(
				'provider'
			),
			'conditions' => array(
				'OauthConnector.id' => $id
			)
		));

		if (empty($data)) {
			return false;
		}
		
		$provider = $data['OauthConnector']['provider'];
		$count = 0;
		if ($provider == self::PROVIDER_GOOGLE) {
			$count = $this->LdapAuthGoogleOauth->find('count', array(
				'conditions' => array(
					'LdapAuthGoogleOauth.oauth_google_id' => $id,
				)
			));
		}
		
		return $count;
	}
}
