<?php
use Phinx\Seed\AbstractSeed;

/**
 * Setting seed.
 */
class SettingSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '2',
                'active' => '1',
                'name' => 'DB Schema Version',
                'variable' => 'DB_SCHEMA_VERSION',
                'value' => 'e1.0.1.015',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'text',
                'options' => NULL,
                'hidden' => '1',
                'required' => '0',
                'setting_group_slug' => NULL,
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2017-02-22 21:32:39',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '3',
                'active' => '1',
                'name' => 'Client ID',
                'variable' => 'CLIENT_ID',
                'value' => NULL,
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'text',
                'options' => NULL,
                'hidden' => '1',
                'required' => '0',
                'setting_group_slug' => NULL,
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2016-11-18 14:37:22',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '4',
                'active' => '1',
                'name' => 'Bruteforce wrong logins',
                'variable' => 'BRUTEFORCE_WRONG_LOGINS',
                'value' => '3',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'number',
                'options' => '{"min":1,"max":10,"step":1}',
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'BFP',
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '5',
                'active' => '1',
                'name' => 'Bruteforce second ago',
                'variable' => 'BRUTEFORCE_SECONDS_AGO',
                'value' => '60',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'number',
                'options' => '{"min":10,"max":120,"step":1}',
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'BFP',
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '10',
                'active' => '1',
                'name' => 'Default currency',
                'variable' => 'DEFAULT_CURRENCY',
                'value' => 'EUR',
                'default_value' => NULL,
                'values' => 'configDefaultCurrency',
                'type' => 'select',
                'options' => '{"AUD":"AUD","CAD":"CAD","USD":"USD","EUR":"EUR","GBP":"GBP","JPY":"JPY"}',
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'CUE',
                'setting_type' => 'config',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '11',
                'active' => '1',
                'name' => 'Type',
                'variable' => 'SMTP_USE',
                'value' => '0',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'select',
                'options' => '{"0":"Mail","1":"SMTP"}',
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'MAILCNF',
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '12',
                'active' => '1',
                'name' => 'SMTP host',
                'variable' => 'SMTP_HOST',
                'value' => '',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'text',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'MAILCNF',
                'setting_type' => 'constant',
                'order' => '1',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '13',
                'active' => '1',
                'name' => 'SMTP user',
                'variable' => 'SMTP_USER',
                'value' => '',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'text',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'MAILCNF',
                'setting_type' => 'constant',
                'order' => '3',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '14',
                'active' => '1',
                'name' => 'SMTP password',
                'variable' => 'SMTP_PWD',
                'value' => '',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'password',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'MAILCNF',
                'setting_type' => 'constant',
                'order' => '4',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '15',
                'active' => '1',
                'name' => 'SMTP timeout',
                'variable' => 'SMTP_TIMEOUT',
                'value' => '60',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'number',
                'options' => '{"min":1,"max":120,"step":1}',
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'MAILCNF',
                'setting_type' => 'constant',
                'order' => '5',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '16',
                'active' => '1',
                'name' => 'SMTP port',
                'variable' => 'SMTP_PORT',
                'value' => '',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'text',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'MAILCNF',
                'setting_type' => 'constant',
                'order' => '6',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '18',
                'active' => '1',
                'name' => 'No reply Email',
                'variable' => 'NO_REPLY_EMAIL',
                'value' => 'noreply@domain.org',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'text',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'MAILCNF',
                'setting_type' => 'constant',
                'order' => '7',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '19',
                'active' => '1',
                'name' => 'Cron security key',
                'variable' => 'CRON_SECURITY_KEY',
                'value' => 'egkrjng328525798',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'text',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'SECKEY',
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '20',
                'active' => '1',
                'name' => 'Bruteforce ban from minutes',
                'variable' => 'BRUTEFORCE_BAN_FOR_MINUTES',
                'value' => '5',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'number',
                'options' => '{"min":1,"max":120,"step":1}',
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'BFP',
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '21',
                'active' => '1',
                'name' => 'Banners off',
                'variable' => 'BANNERS_OFF',
                'value' => '1',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'checkbox',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'BANNER',
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '22',
                'active' => '1',
                'name' => 'Debug',
                'variable' => 'DEBUG',
                'value' => '0',
                'default_value' => NULL,
                'values' => 'configDebug',
                'type' => 'checkbox',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'DEBUGCFG',
                'setting_type' => 'config',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '23',
                'active' => '1',
                'name' => 'Email Debug',
                'variable' => 'EMAIL_DEBUG',
                'value' => '0',
                'default_value' => NULL,
                'values' => 'configEmailDebug',
                'type' => 'checkbox',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'DEBUGCFG',
                'setting_type' => 'config',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '24',
                'active' => '1',
                'name' => 'Risk Appetite',
                'variable' => 'RISK_APPETITE',
                'value' => '1',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'number',
                'options' => '{"min":0,"max":9999,"step":1}',
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'RISKAPPETITE',
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '25',
                'active' => '1',
                'name' => 'Encryption',
                'variable' => 'USE_SSL',
                'value' => '0',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'select',
                'options' => '{"0":"No Encryption","1":"SSL","2":"TLS"}',
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'MAILCNF',
                'setting_type' => 'constant',
                'order' => '2',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '26',
                'active' => '1',
                'name' => 'Timezone',
                'variable' => 'TIMEZONE',
                'value' => NULL,
                'default_value' => NULL,
                'values' => 'configTimezone',
                'type' => 'select',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'TZONE',
                'setting_type' => 'config',
                'order' => '0',
                'modified' => '2015-12-19 00:00:00',
                'created' => '2015-12-19 00:00:00',
            ],
            [
                'id' => '27',
                'active' => '1',
                'name' => 'Backups Enabled',
                'variable' => 'BACKUPS_ENABLED',
                'value' => '0',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'checkbox',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'BACKUP',
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2017-02-22 21:32:29',
                'created' => '2017-02-22 21:32:29',
            ],
            [
                'id' => '28',
                'active' => '1',
                'name' => 'Backup Day Period',
                'variable' => 'BACKUP_DAY_PERIOD',
                'value' => '1',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'select',
                'options' => '{"1":"Every day","2":"Every 2 days","3":"Every 3 days","4":"Every 4 days","5":"Every 5 days","6":"Every 6 days","7":"Every 7 days"}',
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'BACKUP',
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2017-02-22 21:32:29',
                'created' => '2017-02-22 21:32:29',
            ],
            [
                'id' => '29',
                'active' => '1',
                'name' => 'Backup Files Limit',
                'variable' => 'BACKUP_FILES_LIMIT',
                'value' => '15',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'select',
                'options' => '{"1":"1","5":"5","10":"10","15":"15"}',
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'BACKUP',
                'setting_type' => 'constant',
                'order' => '0',
                'modified' => '2017-02-22 21:32:29',
                'created' => '2017-02-22 21:32:29',
            ],
            [
                'id' => '30',
                'active' => '1',
                'name' => 'Name',
                'variable' => 'EMAIL_NAME',
                'value' => '',
                'default_value' => NULL,
                'values' => NULL,
                'type' => 'text',
                'options' => NULL,
                'hidden' => '0',
                'required' => '0',
                'setting_group_slug' => 'MAILCNF',
                'setting_type' => 'constant',
                'order' => '6',
                'modified' => '2017-02-22 21:32:29',
                'created' => '2017-02-22 21:32:29',
            ],
        ];

        $table = $this->table('settings');
        $table->insert($data)->save();
    }
}
